apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.result.name }}
  name: {{ .Values.result.name }}
spec:
  type: NodePort
  ports:
    - name: "result-service"
      port: {{ .Values.result.servicePort }}
      targetPort: {{ .Values.result.containerPort }}
      nodePort: {{ .Values.result.nodePort }}
  selector:
    app: {{ .Values.result.name }}
