apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.result.name }}
  name: {{ .Values.result.name }}
spec:
  replicas: {{ .Values.result.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.result.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.result.name }}
    spec:
      containers:
        - image: {{ .Values.result.image }}
          name: {{ .Values.result.containerName }}
          ports:
            - containerPort: {{ .Values.result.containerPort }}
              name: result