apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.db.name }}
  name: {{ .Values.db.name }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
        - image: {{ .Values.db.image }}
          name: {{ .Values.db.containerName }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password }}
          ports:
            - containerPort: {{ .Values.db.port }}
              name: postgres
          volumeMounts:
            - mountPath: {{ .Values.db.mountPath }}
              name: db-data
      volumes:
        - name: db-data
          emptyDir: {}
