apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.db.name }}
  name: {{ .Values.db.name }}
spec:
  type: ClusterIP
  ports:
    - name: "db-service"
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    app: {{ .Values.db.name }}
