apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.worker.name }}
  name: {{ .Values.worker.name }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.worker.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.worker.name }}
    spec:
      containers:
        - image: {{ .Values.worker.image }}
          name: {{ .Values.worker.containerName }}