apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.redis.name }}
  name: {{ .Values.redis.name }}
spec:
  type: ClusterIP
  ports:
    - name: "redis-service"
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  selector:
    app: {{ .Values.redis.name }}
