apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - charts/db-chart
  - charts/redis-chart
  - charts/result-chart
  - charts/vote-chart
  - charts/worker-chart

configMapGenerator:
  - name: chart-hash
    literals:
      - CHART_HASH=${CHART_HASH}
