apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.vote.name }}
  name: {{ .Values.vote.name }}
spec:
  replicas: {{ .Values.vote.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.vote.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.vote.name }}
    spec:
      containers:
        - image: {{ .Values.vote.image }}
          name: {{ .Values.vote.containerName }}
          ports:
            - containerPort: {{ .Values.vote.containerPort }}
              name: vote