apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.vote.name }}
  name: {{ .Values.vote.name }}
spec:
  type: NodePort
  ports:
    - name: "vote-service"
      port: {{ .Values.vote.servicePort }}
      targetPort: {{ .Values.vote.containerPort }}
      nodePort: {{ .Values.vote.nodePort }}
  selector:
    app: {{ .Values.vote.name }}
